import type { Metadata } from "next";
import { Bricolage_Grotesque, Lato } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Footer2 from "@/components/Footer2";
import Header2 from "@/components/Header2";
import WhatsAppFloatingButton from "@/components/WhatsAppFloatingButton";

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
  display: "swap",
  weight: ["200","300","400", "500", "600", "700", "800"],
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  display: "swap",
  weight: [ "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${bricolageGrotesque.variable} antialiased min-h-screen`}
      >
        <div className="flex min-h-screen flex-col">
          {/* <Header /> */}
          <Header2/>
          <main className="flex-1">{children}</main>
          {/* <Footer /> */}
          <Footer2/>
          <WhatsAppFloatingButton/>
        </div>
      </body>
    </html>
  );
}
