import type { Metadata } from "next";
import { Bricolage_Grotesque, Playfair_Display } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Footer2 from "@/components/Footer2";
import Header2 from "@/components/Header2";
import WhatsAppFloatingButton from "@/components/WhatsAppFloatingButton";
import NextTopLoader from "nextjs-toploader";

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
  display: "swap",
  weight: ["200","300","400", "500", "600", "700", "800"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplay.variable} ${bricolageGrotesque.variable} antialiased`}
      >
        {/* <div className="flex min-h-screen flex-col"> */}
          {/* <Header /> */}
           <NextTopLoader
          color="#7c3aed"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false}
          easing="ease"
          speed={200}
        />
          <Header2/>
          <main className="flex-1">{children}</main>
          {/* <Footer /> */}
          <Footer2/>
          <WhatsAppFloatingButton/>
        {/* </div> */}
      </body>
    </html>
  );
}
